# Generated by Django 3.0 on 2019-12-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0002_auto_20191214_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
