# Generated by Django 3.0 on 2019-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0004_auto_20191215_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
