# Generated by Django 3.0 on 2019-12-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0005_person_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
            ],
        ),
    ]
