# Generated by Django 3.0 on 2019-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0006_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
    ]
