# Generated by Django 3.0 on 2019-12-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0007_company_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dirty',
            field=models.BooleanField(default=True),
        ),
    ]
