# Generated by Django 3.0 on 2019-12-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0008_auto_20191217_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='dirty',
        ),
    ]
